server:
  port: 10011

spring:
  datasource:
    url: jdbc:mysql://122.51.179.89:3306/bank?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 920919
    driver-class-name: com.mysql.cj.jdbc.Driver