server:
  port: 10011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lesliebank?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver